// submissions/vue/Ease.vue
<template>
  <component
    :is="as"
    :class="computedClasses"
    :style="computedStyles"
    @mouseenter="onMouseEnter"
    @mouseleave="onMouseLeave"
  >
    <slot></slot>
  </component>
</template>

<script>
export default {
  name: 'Ease',
  props: {
    animation: {
      type: String,
      default: 'fade-in'
    },
    trigger: {
      type: Boolean,
      default: undefined
    },
    loop: {
      type: Boolean,
      default: false
    },
    delay: {
      type: Number,
      default: 0
    },
    speed: {
      type: String,
      default: 'normal',
      validator: (val) => ['fast', 'normal', 'slow'].includes(val)
    },
    hover: {
      type: Boolean,
      default: false
    },
    as: {
      type: String,
      default: 'div'
    }
  },
  data() {
    return {
      isActive: false
    };
  },
  computed: {
    computedClasses() {
      const animationClass = `ease-${this.animation}`;
      
      const modifiers = [];
      if (this.loop) modifiers.push('ease-loop');
      if (this.hover) modifiers.push('ease-hover');
      if (this.speed === 'fast') modifiers.push('ease-fast');
      if (this.speed === 'slow') modifiers.push('ease-slow');
      
      // Determine if we should show animation
      // If trigger is provided, we respect that. If not, and it's not a hover animation, it's active.
      let currentlyActive = false;
      if (this.trigger !== undefined) {
        currentlyActive = this.trigger;
      } else if (!this.hover) {
        currentlyActive = this.isActive;
      } else {
        currentlyActive = this.isActive;
      }

      const activeClass = (currentlyActive || this.hover) ? animationClass : '';

      return [activeClass, ...modifiers].filter(Boolean).join(' ');
    },
    computedStyles() {
      if (this.delay > 0) {
        return { animationDelay: `${this.delay}ms` };
      }
      return {};
    }
  },
  watch: {
    trigger(newVal) {
      if (newVal !== undefined) {
        this.isActive = newVal;
      }
    }
  },
  mounted() {
    if (this.trigger === undefined && !this.hover) {
      // Trigger animation on mount
      this.isActive = true;
    }
  },
  methods: {
    onMouseEnter() {
      if (this.hover) {
        this.isActive = true;
      }
    },
    onMouseLeave() {
      if (this.hover) {
        this.isActive = false;
      }
    }
  }
};
</script>

// submissions/react/Ease.jsx
import React, { useEffect, useRef, useState } from 'react';

/**
 * EaseMotion Wrapper Component
 * @param {string} animation - The name of the animation (e.g. 'fade-in', 'bounce')
 * @param {boolean} trigger - A boolean that triggers the animation (if not provided, it will animate on mount)
 * @param {boolean} loop - Whether the animation should loop infinitely
 * @param {number} delay - Animation delay in milliseconds
 * @param {string} speed - Speed modifier: 'fast', 'slow', or 'normal' (default)
 * @param {boolean} hover - If true, the animation only triggers on hover
 * @param {React.ElementType} as - The HTML element to render (default is 'div')
 * @param {string} className - Additional CSS classes
 * @param {React.ReactNode} children - Component children
 */
const Ease = ({
  animation = 'fade-in',
  trigger,
  loop = false,
  delay = 0,
  speed = 'normal',
  hover = false,
  as: Component = 'div',
  className = '',
  children,
  ...props
}) => {
  const [isActive, setIsActive] = useState(false);
  const elementRef = useRef(null);

  // Determine if it should animate automatically on mount
  useEffect(() => {
    if (trigger === undefined && !hover) {
      setIsActive(true);
    } else if (trigger !== undefined) {
      setIsActive(trigger);
    }
  }, [trigger, hover]);

  // Construct the CSS classes based on props
  const animationClass = `ease-${animation}`;
  
  // Handling modifiers
  const modifiers = [];
  if (loop) modifiers.push('ease-loop'); // Assuming we have a loop modifier, or we map it to looping animations
  if (hover) modifiers.push('ease-hover'); 
  if (speed === 'fast') modifiers.push('ease-fast');
  if (speed === 'slow') modifiers.push('ease-slow');

  // We conditionally add the animation class if it's active or if it's a hover animation
  const classes = [
    className,
    (isActive || hover) ? animationClass : '',
    ...modifiers
  ].filter(Boolean).join(' ').trim();

  const inlineStyles = delay > 0 ? { animationDelay: `${delay}ms` } : {};

  return (
    <Component
      ref={elementRef}
      className={classes}
      style={{ ...props.style, ...inlineStyles }}
      onMouseEnter={() => hover && setIsActive(true)}
      onMouseLeave={() => hover && setIsActive(false)}
      {...props}
    >
      {children}
    </Component>
  );
};

export default Ease;
